import { StyleSheet } from 'react-native';
import { spacing } from '../theme/tokens';

export const darkPalette = {
  backgroundTop: '#2b283eff',
  backgroundBottom: '#171026',
  screenGlow: 'rgba(0, 230, 118, 0.18)',
  screenGlowSoft: 'rgba(213, 0, 249, 0.15)',
  screenGlowAccent: 'rgba(0, 176, 255, 0.18)',
  surface: 'rgba(240, 238, 238, 1)',
  surfaceSoft: 'rgba(255, 255, 255, 0.1)',
  surfaceInset: 'rgba(0, 0, 0, 0.25)',
  border: 'rgba(255, 255, 255, 0.08)',
  divider: 'rgba(255, 255, 255, 0.05)',
  text: '#ffffff',
  textMuted: '#e2e8f0',
  textSoft: '#94a3b8',
  green: '#00ff9d',
  greenSoft: 'rgba(0, 255, 157, 0.1)',
  purple: '#d946ef',
  purpleSoft: 'rgba(217, 70, 239, 0.1)',
  blue: '#38bdf8',
  blueSoft: 'rgba(56, 189, 248, 0.1)',
  danger: '#ef4444',
  inactive: '#64748b',
  shadow: 'rgba(83, 79, 79, 0.6)',
};

export const lightPalette = {
  backgroundTop: '#f4fbf7',
  backgroundBottom: '#f0f4f8',
  screenGlow: 'rgba(5, 148, 50, 0.05)',
  screenGlowSoft: 'rgba(50, 146, 255, 0.04)',
  screenGlowAccent: 'rgba(149, 92, 255, 0.03)',
  surface: '#ffffff',
  surfaceSoft: '#f0f4f6',
  surfaceInset: '#f7fafb',
  border: 'rgba(0, 0, 0, 0.08)',
  divider: 'rgba(0, 0, 0, 0.05)',
  text: '#111827',
  textMuted: '#4b5563',
  textSoft: '#6b7280',
  green: '#059432ff',
  greenSoft: 'rgba(34, 228, 94, 0.1)',
  purple: '#955cff',
  purpleSoft: 'rgba(149, 92, 255, 0.1)',
  blue: '#3292ff',
  blueSoft: 'rgba(50, 146, 255, 0.1)',
  danger: '#ef4444',
  inactive: '#d1d5db',
  shadow: 'rgba(0, 0, 0, 0.08)',
};

export type ScreenPalette = typeof darkPalette;

export const fontFamily = {
  regular: 'Roboto_400Regular',
  medium: 'Roboto_500Medium',
  semiBold: 'Roboto_600SemiBold',
  bold: 'Roboto_700Bold',
  extraBold: 'Roboto_800ExtraBold',
  black: 'Roboto_900Black',
} as const;

export function createControlStyles(palette: ScreenPalette, mode: 'light' | 'dark') {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: palette.backgroundTop,
    },
    content: {
      paddingHorizontal: 18,
      paddingTop: spacing.sm,
    },
    heroSection: {
      minHeight: 190,
      overflow: 'hidden',
      position: 'relative',
    },
    heroArt: {
      position: 'absolute',
      top: 18,
      right: 4,
      width: 156,
      height: 146,
      alignItems: 'center',
      justifyContent: 'center',
      opacity: 0.7,
    },
    heroRingOuter: {
      position: 'absolute',
      width: 154,
      height: 154,
      borderRadius: 77,
      borderWidth: 1,
      borderColor: 'rgba(18, 229, 85, 0.12)',
    },
    heroRingMiddle: {
      position: 'absolute',
      width: 112,
      height: 112,
      borderRadius: 56,
      borderWidth: 1,
      borderColor: 'rgba(34, 228, 94, 0.14)',
      backgroundColor: 'rgba(34, 228, 94, 0.04)',
    },
    heroShield: {
      width: 88,
      height: 88,
      borderRadius: 44,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(34, 228, 94, 0.05)',
    },
    topBar: {
      zIndex: 2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    topIconButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      borderWidth: 1,
      borderColor: palette.border,
    },
    topTitle: {
      zIndex: 2,
      fontSize: 22,
      fontFamily: fontFamily.extraBold,
      color: palette.text,
    },
    helperText: {
      zIndex: 2,
      marginTop: spacing.xl,
      maxWidth: 228,
      fontSize: 17,
      lineHeight: 29,
      fontFamily: fontFamily.medium,
      color: palette.textSoft,
    },
    metricsRow: {
      marginTop: spacing.md,
      flexDirection: 'row',
      gap: spacing.sm,
    },
    metricCard: {
      flex: 1,
      minHeight: 88,
      borderRadius: 22,
      paddingHorizontal: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surface,
      shadowColor: palette.shadow,
      shadowOpacity: 0.18,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 5,
    },
    metricIcon: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
    },
    metricCopy: {
      flex: 1,
    },
    metricValue: {
      fontSize: 26,
      lineHeight: 28,
      fontFamily: fontFamily.black,
      letterSpacing: 0,
    },
    metricLabel: {
      marginTop: 3,
      fontSize: 10,
      fontFamily: fontFamily.extraBold,
      color: palette.text,
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    metricCaption: {
      marginTop: 4,
      fontSize: 10,
      fontFamily: fontFamily.medium,
      color: palette.textSoft,
    },
    searchShell: {
      marginTop: spacing.md,
      minHeight: 64,
      borderRadius: 24,
      paddingHorizontal: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: palette.border,
    },
    searchInput: {
      flex: 1,
      fontSize: 17,
      fontFamily: fontFamily.regular,
      color: palette.text,
    },
    card: {
      marginTop: spacing.md,
      borderRadius: 24,
      padding: spacing.md,
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: palette.border,
      shadowColor: palette.shadow,
      shadowOpacity: 0.2,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 12 },
      elevation: 6,
    },
    sectionEyebrow: {
      fontSize: 13,
      fontFamily: fontFamily.extraBold,
      color: palette.textSoft,
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    appRow: {
      minHeight: 64,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    appShell: {
      marginTop: spacing.sm,
      borderRadius: 20,
      paddingHorizontal: spacing.md,
      paddingVertical: 8,
      backgroundColor: palette.surfaceSoft,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.04)',
    },
    appShellExpanded: {
      backgroundColor: mode === 'dark' ? 'rgba(26, 36, 41, 0.92)' : '#e4eaed',
    },
    appIdentity: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    appCopy: {
      flex: 1,
    },
    appTitle: {
      fontSize: 18,
      fontFamily: fontFamily.extraBold,
      color: palette.text,
      letterSpacing: 0,
    },
    appSubtitle: {
      marginTop: 3,
      fontSize: 14,
      fontFamily: fontFamily.semiBold,
    },
    appSubtitleAvailable: {
      color: palette.green,
    },
    appSubtitleBlocked: {
      color: palette.danger,
    },
    appSubtitleRule: {
      color: palette.purple,
    },
    appActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    optionPanel: {
      marginTop: 8,
      marginBottom: 6,
      borderRadius: 20,
      paddingHorizontal: spacing.md,
      backgroundColor: palette.surfaceInset,
    },
    optionRow: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    optionRowDivider: {
      borderTopWidth: 1,
      borderTopColor: palette.divider,
    },
    optionIdentity: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    optionLabel: {
      flex: 1,
      fontSize: 16,
      lineHeight: 22,
      fontFamily: fontFamily.semiBold,
      color: palette.text,
      textTransform: 'capitalize',
    },
    toggleTrack: {
      width: 52,
      height: 30,
      borderRadius: 999,
      paddingHorizontal: 3,
      alignItems: 'center',
      flexDirection: 'row',
      borderWidth: 1,
    },
    toggleThumb: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: '#ffffff',
    },
    viewAllButton: {
      marginTop: spacing.md,
      minHeight: 32,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.xs,
    },
    viewAllText: {
      fontSize: 15,
      fontFamily: fontFamily.extraBold,
      color: palette.green,
    },
    emptyText: {
      marginTop: spacing.md,
      fontSize: 14,
      fontFamily: fontFamily.regular,
      color: palette.textMuted,
    },
    modeRow: {
      minHeight: 58,
      marginTop: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
      borderTopWidth: 1,
      borderTopColor: palette.divider,
      paddingTop: spacing.sm,
    },
    modeRowFirst: {
      borderTopWidth: 0,
    },
    modeIdentity: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    modeIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.greenSoft,
    },
    modeCopy: {
      flex: 1,
    },
    modeTitle: {
      fontSize: 17,
      fontFamily: fontFamily.extraBold,
      color: palette.text,
      letterSpacing: 0,
    },
    modeSubtitle: {
      marginTop: 2,
      fontSize: 14,
      fontFamily: fontFamily.medium,
      color: palette.textSoft,
    },
    permissionCard: {
      marginTop: spacing.xl,
      padding: spacing.lg,
      borderRadius: 24,
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: palette.border,
      shadowColor: palette.shadow,
      shadowOpacity: 0.16,
      shadowRadius: 16,
      elevation: 4,
      alignItems: 'center',
    },
    permissionIcon: {
      alignSelf: 'center',
      marginTop: spacing.md,
    },
    permissionTitle: {
      marginTop: spacing.md,
      fontSize: 22,
      fontFamily: fontFamily.extraBold,
      color: palette.text,
      letterSpacing: 0,
      textAlign: 'center',
    },
    permissionSubtitle: {
      marginTop: spacing.xs,
      fontSize: 14,
      lineHeight: 20,
      fontFamily: fontFamily.medium,
      color: palette.textMuted,
      textAlign: 'center',
      paddingHorizontal: spacing.sm,
    },
    permissionBadgeRow: {
      flexDirection: 'row',
      gap: spacing.sm,
      marginTop: spacing.md,
      justifyContent: 'center',
    },
    permissionBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 99,
      backgroundColor: palette.surfaceSoft,
    },
    permissionBadgeText: {
      fontSize: 12,
      fontFamily: fontFamily.bold,
    },
    permissionBtn: {
      width: '100%',
      marginTop: spacing.xl,
      height: 52,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: palette.green,
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
    },
    permissionBtnText: {
      fontSize: 16,
      fontFamily: fontFamily.extraBold,
      color: '#03100a',
      letterSpacing: 0,
    },
  });
}
