import { StyleSheet } from 'react-native';
import { spacing } from '../theme/tokens';
import { ScreenPalette } from '../theme/screenPalettes';

export function createControlStyles(palette: ScreenPalette, mode: 'light' | 'dark') {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: palette.backgroundTop,
    },
    content: {
      paddingHorizontal: 18,
      paddingTop: spacing.sm,
    },
    heroSection: {
      overflow: 'hidden',
      position: 'relative',
      paddingBottom: spacing.sm,
    },
    heroArt: {
      position: 'absolute',
      top: 18,
      right: 4,
      width: 156,
      height: 146,
      alignItems: 'center',
      justifyContent: 'center',
      opacity: 0.7,
    },
    heroRingOuter: {
      position: 'absolute',
      width: 154,
      height: 154,
      borderRadius: 77,
      borderWidth: 1,
      borderColor: 'rgba(18, 229, 85, 0.12)',
    },
    heroRingMiddle: {
      position: 'absolute',
      width: 112,
      height: 112,
      borderRadius: 56,
      borderWidth: 1,
      borderColor: 'rgba(34, 228, 94, 0.14)',
      backgroundColor: 'rgba(34, 228, 94, 0.04)',
    },
    heroShield: {
      width: 88,
      height: 88,
      borderRadius: 44,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(34, 228, 94, 0.05)',
    },
    topBar: {
      zIndex: 2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    topIconButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: mode === 'dark' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)',
      borderWidth: 1,
      borderColor: palette.border,
    },
    topTitle: {
      zIndex: 2,
      fontSize: 22,
      fontWeight: '800',
      color: palette.text,
    },
    helperText: {
      zIndex: 2,
      marginTop: spacing.sm,
      maxWidth: 228,
      fontSize: 17,
      lineHeight: 29,
      fontWeight: '500',
      color: palette.textSoft,
    },
    metricsRow: {
      marginTop: 0,
      flexDirection: 'row',
      gap: spacing.sm,
    },
    metricCard: {
      flex: 1,
      minHeight: 88,
      borderRadius: 22,
      paddingHorizontal: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surface,
      shadowColor: palette.shadow,
      shadowOpacity: 0.18,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 5,
    },
    metricIcon: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
    },
    metricCopy: {
      flex: 1,
    },
    metricValue: {
      fontSize: 26,
      lineHeight: 28,
      fontWeight: '900',
      letterSpacing: 0,
    },
    metricLabel: {
      marginTop: 3,
      fontSize: 10,
      fontWeight: '800',
      color: palette.text,
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    metricCaption: {
      marginTop: 4,
      fontSize: 10,
      fontWeight: '500',
      color: palette.textSoft,
    },
    searchShell: {
      marginTop: spacing.sm,
      minHeight: 64,
      borderRadius: 24,
      paddingHorizontal: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: palette.border,
    },
    searchInput: {
      flex: 1,
      fontSize: 17,
      fontWeight: '400',
      color: palette.text,
    },
    card: {
      marginTop: spacing.sm,
      borderRadius: 24,
      padding: spacing.md,
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: palette.border,
      shadowColor: palette.shadow,
      shadowOpacity: 0.2,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 12 },
      elevation: 6,
    },
    sectionEyebrow: {
      fontSize: 13,
      fontWeight: '800',
      color: palette.textSoft,
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    appRow: {
      minHeight: 64,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    appShell: {
      marginTop: spacing.sm,
      borderRadius: 20,
      paddingHorizontal: spacing.md,
      paddingVertical: 8,
      backgroundColor: mode === 'dark' ? 'rgba(255,255,255,0.07)' : palette.surfaceSoft,
      borderWidth: 1,
      borderColor: palette.border,
    },
    appShellExpanded: {
      backgroundColor: mode === 'dark' ? 'rgba(26, 36, 41, 0.92)' : '#e4eaed',
    },
    appIdentity: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    appCopy: {
      flex: 1,
    },
    appTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: palette.text,
      letterSpacing: 0,
    },
    appSubtitle: {
      marginTop: 3,
      fontSize: 14,
      fontWeight: '600',
    },
    appSubtitleAvailable: {
      color: palette.green,
    },
    appSubtitleBlocked: {
      color: palette.danger,
    },
    appSubtitleRule: {
      color: palette.purple,
    },
    appActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    optionPanel: {
      marginTop: 8,
      marginBottom: 6,
      borderRadius: 20,
      paddingHorizontal: spacing.md,
      backgroundColor: palette.surfaceInset,
    },
    optionRow: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    optionRowDivider: {
      borderTopWidth: 1,
      borderTopColor: palette.divider,
    },
    optionIdentity: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    optionLabel: {
      flex: 1,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '600',
      color: palette.text,
      textTransform: 'capitalize',
    },
    toggleTrack: {
      width: 50,
      height: 28,
      borderRadius: 14,
      paddingHorizontal: 2,
      alignItems: 'center',
      flexDirection: 'row',
      borderWidth: 1.5,
      borderColor: mode === 'dark' ? '#475569' : '#cbd5e1',
    },
    toggleThumb: {
      width: 22,
      height: 22,
      borderRadius: 11,
    },
    toggleSwitch: {
      transform: [{ scaleX: 0.92 }, { scaleY: 0.92 }],
    },
    viewAllButton: {
      marginTop: spacing.md,
      minHeight: 32,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.xs,
    },
    viewAllText: {
      fontSize: 15,
      fontWeight: '800',
      color: palette.green,
    },
    emptyText: {
      marginTop: spacing.md,
      fontSize: 14,
      fontWeight: '400',
      color: palette.textMuted,
    },
    modeRow: {
      minHeight: 58,
      marginTop: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
      borderTopWidth: 1,
      borderTopColor: palette.divider,
      paddingTop: spacing.sm,
    },
    modeRowFirst: {
      borderTopWidth: 0,
    },
    modeIdentity: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    modeIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.greenSoft,
    },
    modeCopy: {
      flex: 1,
    },
    modeTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: palette.text,
      letterSpacing: 0,
    },
    modeSubtitle: {
      marginTop: 2,
      fontSize: 14,
      fontWeight: '500',
      color: palette.textSoft,
    },
    permissionCard: {
      marginTop: spacing.xl,
      padding: spacing.lg,
      borderRadius: 24,
      backgroundColor: palette.surface,
      borderWidth: 1,
      borderColor: palette.border,
      shadowColor: palette.shadow,
      shadowOpacity: 0.16,
      shadowRadius: 16,
      elevation: 4,
      alignItems: 'center',
    },
    permissionIcon: {
      alignSelf: 'center',
      marginTop: spacing.md,
    },
    permissionTitle: {
      marginTop: spacing.md,
      fontSize: 22,
      fontWeight: '800',
      color: palette.text,
      letterSpacing: 0,
      textAlign: 'center',
    },
    permissionSubtitle: {
      marginTop: spacing.xs,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
      color: palette.textMuted,
      textAlign: 'center',
      paddingHorizontal: spacing.sm,
    },
    permissionBadgeRow: {
      flexDirection: 'row',
      gap: spacing.sm,
      marginTop: spacing.md,
      justifyContent: 'center',
    },
    permissionBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 99,
      backgroundColor: palette.surfaceSoft,
    },
    permissionBadgeText: {
      fontSize: 12,
      fontWeight: '700',
    },
    permissionBtn: {
      width: '100%',
      marginTop: spacing.xl,
      height: 52,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: palette.green,
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
    },
    permissionBtnText: {
      fontSize: 16,
      fontWeight: '800',
      color: '#03100a',
      letterSpacing: 0,
    },
  });
}
