import { StyleSheet } from 'react-native';
import { spacing, typography, radius } from '../theme/tokens';
import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { PlannerCategory } from '../types/models';
import { ScreenPalette } from '../theme/screenPalettes';

export function getCategoryStyles(
  palette: ScreenPalette
): Record<PlannerCategory, { icon: React.ComponentProps<typeof Ionicons>['name']; bg: string; text: string }> {
  return {
    Study: { icon: 'book-outline', bg: palette.blueSoft || '#e4edff', text: palette.blue || '#2e6ff2' },
    Work: { icon: 'briefcase-outline', bg: palette.greenSoft || '#dff5e8', text: palette.green || '#1fa55b' },
    Health: { icon: 'body-outline', bg: palette.goldSoft || '#fff2d7', text: palette.gold || '#d9981f' },
    Personal: { icon: 'sparkles-outline', bg: palette.purpleSoft || '#f3e8ff', text: palette.purple || '#9333ea' },
  };
}

export function createPlannerStyles(palette: ScreenPalette, mode: 'dark' | 'light') {
  return StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.backgroundTop,
  },
  flex: {
    flex: 1,
  },
  content: {
    padding: spacing.md,
    paddingBottom: spacing.xl,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  topIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  topTitle: {
    fontSize: 30,
    fontWeight: '800',
    color: palette.text,
  },
  summaryShell: {
    marginTop: spacing.xs,
    borderRadius: 24,
    padding: spacing.lg,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  summaryTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: palette.text,
  },
  summaryPercent: {
    fontSize: typography.caption,
    fontWeight: '700',
    color: palette.textMuted,
  },
  progressTrack: {
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
    backgroundColor: mode === 'dark' ? 'rgba(255,255,255,0.05)' : '#f3f4f6',
    width: 100,
  },
  progressFill: {
    height: '100%',
    borderRadius: radius.round,
    backgroundColor: palette.green,
  },
  summaryText: {
    marginTop: spacing.md,
    fontSize: 15,
    lineHeight: 23,
    textAlign: 'center',
    color: palette.textMuted,
  },
  liveFocusCard: {
    marginTop: spacing.lg,
    borderRadius: 24,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: mode === 'dark' ? 'rgba(16, 185, 129, 0.08)' : '#f0fdf4',
    borderWidth: 1,
    borderColor: mode === 'dark' ? 'rgba(16, 185, 129, 0.2)' : 'rgba(16, 185, 129, 0.1)',
  },
  liveFocusRing: {
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveFocusCopy: {
    flex: 1,
    marginLeft: spacing.lg,
  },
  liveFocusChip: {
    alignSelf: 'flex-start',
    backgroundColor: mode === 'dark' ? 'rgba(16, 185, 129, 0.15)' : 'rgba(16, 185, 129, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginBottom: 6,
  },
  liveFocusChipText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#10b981',
    letterSpacing: 0.5,
  },
  liveFocusTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: palette.text,
  },
  liveFocusMeta: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  liveFocusMetaText: {
    fontSize: 14,
    fontWeight: '600',
    color: palette.textMuted,
  },
  liveFocusTimerWrap: {
    alignItems: 'flex-end',
    marginRight: spacing.md,
  },
  liveFocusRemaining: {
    fontSize: 26,
    fontWeight: '800',
    color: palette.text,
    letterSpacing: -0.5,
  },
  liveFocusRemainingLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.textMuted,
    marginTop: -2,
  },
  liveFocusButton: {
    width: 52,
    height: 64,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: mode === 'dark' ? 'rgba(16, 185, 129, 0.15)' : 'rgba(16, 185, 129, 0.08)',
    gap: 4,
  },
  liveFocusButtonText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#10b981',
  },
  suggestionsShell: {
    marginTop: spacing.lg,
    borderRadius: 24,
    padding: spacing.md,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  suggestionsLabel: {
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: palette.textSoft,
  },
  suggestionCard: {
    marginTop: spacing.md,
    borderRadius: 22,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: mode === 'dark' ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.02)',
    shadowColor: '#000',
    shadowOpacity: mode === 'dark' ? 0.2 : 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  suggestionIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionCopy: {
    flex: 1,
  },
  suggestionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.text,
  },
  suggestionMeta: {
    marginTop: 4,
    fontSize: 14,
    color: palette.textMuted,
  },
  addSuggestionButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
    shadowColor: palette.green,
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  addSuggestionButtonDisabled: {
    backgroundColor: mode === 'dark' ? 'rgba(16, 185, 129, 0.2)' : '#e0e0e0',
    shadowOpacity: 0,
    elevation: 0,
  },
  addCustomButton: {
    marginTop: spacing.lg,
    minHeight: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
    borderWidth: 1,
    borderColor: palette.green,
  },
  addCustomButtonText: {
    fontSize: 17,
    fontWeight: '800',
    color: palette.green,
  },
  composerCard: {
    marginTop: spacing.lg,
    borderRadius: 32,
    padding: 24,
    backgroundColor: mode === 'dark' ? 'rgba(30, 32, 44, 0.95)' : '#ffffff',
    borderWidth: 1,
    borderColor: mode === 'dark' ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.05)',
    shadowColor: palette.blue,
    shadowOpacity: mode === 'dark' ? 0.4 : 0.12,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  composerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  composerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: palette.text,
  },
  composerHide: {
    fontSize: 15,
    fontWeight: '700',
    color: palette.textMuted,
  },
  inputShell: {
    marginTop: spacing.md,
  },
  inputLabel: {
    marginBottom: spacing.xs,
    fontSize: typography.caption,
    fontWeight: '700',
    color: palette.textMuted,
  },
  primaryInput: {
    minHeight: 56,
    borderRadius: 20,
    paddingHorizontal: 16,
    backgroundColor: mode === 'dark' ? 'rgba(255,255,255,0.03)' : '#f8f9fa',
    color: palette.text,
    borderWidth: 1.5,
    borderColor: mode === 'dark' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)',
    fontSize: 16,
    fontWeight: '600',
  },
  secondaryInput: {
    minHeight: 52,
    borderRadius: 18,
    paddingHorizontal: 16,
    backgroundColor: mode === 'dark' ? 'rgba(255,255,255,0.03)' : '#f8f9fa',
    color: palette.text,
    borderWidth: 1.5,
    borderColor: mode === 'dark' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)',
    fontSize: 15,
    fontWeight: '700',
  },
  inlineInputs: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  halfInput: {
    flex: 1,
  },
  categoriesWrap: {
    marginTop: spacing.md,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: mode === 'dark' ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.03)',
    backgroundColor: mode === 'dark' ? 'rgba(255,255,255,0.02)' : '#ffffff',
  },
  categoryChipLabel: {
    fontSize: typography.caption,
    fontWeight: '700',
  },
  saveButton: {
    marginTop: spacing.xl,
    minHeight: 58,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
    shadowColor: palette.green,
    shadowOpacity: 0.35,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  saveButtonText: {
    fontSize: 17,
    fontWeight: '800',
    color: '#ffffff',
  },
  tasksSectionHeader: {
    marginTop: spacing.md,
    marginBottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tasksSectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: palette.text,
  },
  tasksSectionMeta: {
    fontSize: typography.caption,
    fontWeight: '700',
    color: palette.textMuted,
  },
  emptyCard: {
    borderRadius: 22,
    padding: spacing.lg,
    alignItems: 'center',
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.stroke,
    shadowColor: palette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  emptyText: {
    fontSize: 15,
    color: palette.textMuted,
  },
  taskCard: {
    marginBottom: spacing.md,
    borderRadius: 24,
    padding: 16,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  taskTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  taskIdentity: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  taskIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskCopy: {
    flex: 1,
  },
  taskTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: palette.text,
  },
  taskTitleCompleted: {
    textDecorationLine: 'line-through',
    color: palette.textMuted,
    opacity: 0.7,
  },
  taskCardCompleted: {
    opacity: 0.85,
    backgroundColor: mode === 'dark' ? 'rgba(255,255,255,0.02)' : '#fafafa',
  },
  completedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: mode === 'dark' ? 'rgba(16, 185, 129, 0.2)' : '#dcfce7',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  completedBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: palette.green,
    textTransform: 'uppercase',
  },
  taskMeta: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: '600',
    color: palette.textMuted,
  },
  openButton: {
    backgroundColor: mode === 'dark' ? 'rgba(59, 130, 246, 0.1)' : '#f0f7ff',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  openButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: palette.blue,
  },
  actionsGrid: {
    marginTop: spacing.lg,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  quickAction: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  quickActionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.text,
  },
  quickActionDanger: {
    backgroundColor: mode === 'dark' ? 'rgba(239, 68, 68, 0.1)' : 'rgba(239, 68, 68, 0.05)',
  },
  quickActionSuccess: {
    backgroundColor: mode === 'dark' ? 'rgba(16, 185, 129, 0.1)' : 'rgba(16, 185, 129, 0.05)',
  },
  quickActionPrimary: {
    backgroundColor: mode === 'dark' ? 'rgba(59, 130, 246, 0.1)' : 'rgba(59, 130, 246, 0.05)',
  },
  });
}
