import { StyleSheet } from 'react-native';
import { spacing } from '../theme/tokens';
import { ScreenPalette } from '../theme/screenPalettes';

export function createFocusStyles(palette: ScreenPalette, mode: 'light' | 'dark') {
  return StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.backgroundTop,
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xs,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  topTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.text,
  },
  focusHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 0,
    marginBottom: spacing.sm,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  modeChip: {
    minHeight: 38,
    borderRadius: 19,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: mode === 'dark' ? 'rgba(255,255,255,0.08)' : 'rgba(255,255,255,1)',
    borderWidth: 1,
    borderColor: palette.stroke,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  modeMenu: {
    position: 'absolute',
    top: 44,
    right: 0,
    width: 220,
    zIndex: 100,
    borderRadius: 16,
    padding: 6,
    backgroundColor: mode === 'dark' ? '#1a1b26' : '#ffffff',
    borderWidth: 1,
    borderColor: palette.stroke,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 10,
  },
  modeOption: {
    borderRadius: 16,
    padding: spacing.md,
  },
  modeOptionActive: {
    backgroundColor: mode === 'dark' ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.03)',
  },
  modeOptionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.text,
  },
  modeOptionMeta: {
    marginTop: 4,
    fontSize: 14,
    color: palette.textSoft,
  },
  modeChipText: {
    fontSize: 14,
    fontWeight: '800',
    color: palette.text,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: '900',
    color: palette.text,
    flex: 1,
    textAlign: 'left',
    letterSpacing: -0.4,
  },
  subtitleAccent: {
    color: palette.green,
  },
  ringSection: {
    marginTop: spacing.sm,
    marginBottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 300,
  },
  ringAtmosphere: {
    position: 'absolute',
  },
  ringShell: {
    borderRadius: 146,
    backgroundColor: 'transparent',
    shadowColor: '#7be18a',
    shadowOpacity: 0.12,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 0 },
    elevation: 4,
  },
  ringCenterDisc: {
    position: 'absolute',
    width: 248,
    height: 248,
    borderRadius: 124,
    borderWidth: 1,
    borderColor: palette.ringDiscBorder,
    backgroundColor: palette.ringDisc,
    shadowColor: palette.ringDiscShadow,
    shadowOpacity: palette.ringDiscShadowOpacity,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  ringOverlay: {
    position: 'absolute',
    top: 88,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerValue: {
    fontSize: 56,
    lineHeight: 64,
    fontWeight: '900',
    letterSpacing: -2,
    color: palette.green,
  },
  timerState: {
    marginTop: spacing.xs,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: palette.textMuted,
  },
  centerAction: {
    position: 'absolute',
    bottom: 46,
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    shadowColor: palette.shadow,
    shadowOpacity: 0.4,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 9,
  },
  goalCard: {
    marginTop: spacing.sm,
    borderRadius: 24,
    padding: spacing.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  goalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  goalLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: palette.textMuted,
  },
  goalValue: {
    marginTop: spacing.sm,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    letterSpacing: -1,
    color: palette.text,
  },
  goalTrack: {
    marginTop: spacing.md,
    height: 8,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: palette.ringTrack,
  },
  goalFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: palette.green,
  },
  editCard: {
    marginTop: spacing.md,
    borderRadius: 24,
    padding: spacing.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.stroke,
    shadowColor: palette.shadow,
    shadowOpacity: 0.15,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  editHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  editTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.text,
    letterSpacing: -0.2,
  },
  editMeta: {
    fontSize: 14,
    fontWeight: '500',
    color: palette.textMuted,
  },
  presetRow: {
    marginTop: spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  presetChip: {
    flex: 1,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  presetChipActive: {
    backgroundColor: palette.greenSoft,
    borderColor: palette.green,
  },
  presetChipText: {
    fontSize: 14,
    fontWeight: '600',
    color: palette.textMuted,
  },
  presetChipTextActive: {
    color: palette.greenDeep,
    fontWeight: '800',
  },
  editRow: {
    marginTop: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  editStepButton: {
    minWidth: 68,
    minHeight: 52,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceButton,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  editInputShell: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  editInput: {
    minWidth: 48,
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: -1,
    textAlign: 'center',
    color: palette.text,
  },
  editUnit: {
    marginLeft: spacing.xs,
    fontSize: 15,
    fontWeight: '600',
    color: palette.textMuted,
  },
  editActions: {
    marginTop: spacing.md,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  editGhostButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  editGhostText: {
    fontSize: 15,
    fontWeight: '700',
    color: palette.textMuted,
  },
  editApplyButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenDeep,
  },
  editApplyText: {
    fontSize: 15,
    fontWeight: '700',
    color: palette.white,
  },
  bottomActions: {
    marginTop: spacing.md,
    marginBottom: spacing.sm,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  actionButton: {
    flex: 1,
    minHeight: 72,
    borderRadius: 22,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    backgroundColor: palette.surfaceButton,
    borderWidth: 1,
    borderColor: palette.stroke,
    shadowColor: palette.shadow,
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  actionCopy: {
    alignItems: 'flex-start',
  },
  actionLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.text,
  },
  actionHint: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: palette.textMuted,
  },
  });
}
