import { StyleSheet } from 'react-native';
import { spacing } from '../theme/tokens';

export const darkPalette = {
  backgroundTop: '#0f111a',
  backgroundBottom: '#181124',
  screenGlow: 'rgba(0, 255, 170, 0.25)',
  screenGlowSoft: 'rgba(255, 51, 153, 0.2)',
  screenGlowAccent: 'rgba(51, 153, 255, 0.25)',
  surface: 'rgba(255, 255, 255, 0.12)',
  surfaceSoft: 'rgba(255, 255, 255, 0.08)',
  surfaceButton: 'rgba(255, 255, 255, 0.15)',
  stroke: 'rgba(255, 255, 255, 0.2)',
  text: '#ffffff',
  textMuted: '#e2e8f0',
  textSoft: '#94a3b8',
  green: '#00ff9d',
  greenGlow: 'rgba(0, 255, 157, 0.25)',
  greenDeep: '#00cc7e',
  greenSoft: 'rgba(0, 255, 157, 0.25)',
  white: '#ffffff',
  shadow: 'rgba(0, 0, 0, 0.5)',
  ringTrack: 'rgba(0, 255, 157, 0.25)',
  ringDisc: 'rgba(20, 20, 30, 0.6)',
  ringGlowSolid: '#00ff9d',
  ringDiscBorder: 'rgba(255, 255, 255, 0.15)',
  ringDiscShadow: '#000000',
  ringDiscShadowOpacity: 0.8,
};

export const lightPalette = {
  backgroundTop: '#e8f5e9',
  backgroundBottom: '#f3e5f5',
  screenGlow: 'rgba(0, 200, 83, 0.15)',
  screenGlowSoft: 'rgba(170, 0, 255, 0.12)',
  screenGlowAccent: 'rgba(41, 98, 255, 0.15)',
  surface: 'rgba(255, 255, 255, 0.8)',
  surfaceSoft: 'rgba(255, 255, 255, 0.6)',
  surfaceButton: 'rgba(255, 255, 255, 0.9)',
  stroke: 'rgba(255, 255, 255, 0.9)',
  text: '#0f172a',
  textMuted: '#475569',
  textSoft: '#94a3b8',
  green: '#00c853',
  greenGlow: 'rgba(0, 200, 83, 0.2)',
  greenDeep: '#00a344',
  greenSoft: 'rgba(0, 200, 83, 0.15)',
  white: '#ffffff',
  shadow: 'rgba(0, 0, 0, 0.06)',
  ringTrack: 'rgba(16, 185, 129, 0.2)',
  ringDisc: 'rgba(255, 255, 255, 0.8)',
  ringGlowSolid: '#00c853',
  ringDiscBorder: 'rgba(255, 255, 255, 1)',
  ringDiscShadow: 'rgba(0, 0, 0, 0.1)',
  ringDiscShadowOpacity: 0.12,
};

export type ScreenPalette = typeof darkPalette & {
  screenGlow: string;
  screenGlowSoft: string;
  screenGlowAccent: string;
};

export function createFocusStyles(palette: ScreenPalette) {
  return StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.backgroundTop,
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  topTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.text,
  },
  modeChip: {
    marginTop: spacing.xl,
    alignSelf: 'center',
    minHeight: 44,
    borderRadius: 22,
    paddingHorizontal: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  modeMenu: {
    marginTop: spacing.sm,
    borderRadius: 20,
    padding: spacing.sm,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  modeOption: {
    borderRadius: 16,
    padding: spacing.md,
  },
  modeOptionActive: {
    backgroundColor: palette.surfaceSoft,
  },
  modeOptionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.text,
    letterSpacing: -0.2,
  },
  modeOptionMeta: {
    marginTop: 4,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '500',
    color: palette.textMuted,
  },
  modeChipText: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.text,
  },
  subtitle: {
    marginTop: spacing.lg,
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'center',
    color: palette.textMuted,
    maxWidth: 240,
    alignSelf: 'center',
  },
  ringSection: {
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 320,
  },
  ringAtmosphere: {
    position: 'absolute',
  },
  ringShell: {
    borderRadius: 146,
    backgroundColor: 'transparent',
    shadowColor: '#7be18a',
    shadowOpacity: 0.12,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 0 },
    elevation: 4,
  },
  ringCenterDisc: {
    position: 'absolute',
    width: 248,
    height: 248,
    borderRadius: 124,
    borderWidth: 1,
    borderColor: palette.ringDiscBorder,
    backgroundColor: palette.ringDisc,
    shadowColor: palette.ringDiscShadow,
    shadowOpacity: palette.ringDiscShadowOpacity,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  ringOverlay: {
    position: 'absolute',
    top: 88,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerValue: {
    fontSize: 56,
    lineHeight: 64,
    fontWeight: '900',
    letterSpacing: -2,
    color: palette.green,
  },
  timerState: {
    marginTop: spacing.xs,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: palette.textMuted,
  },
  centerAction: {
    position: 'absolute',
    bottom: 46,
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    shadowColor: palette.shadow,
    shadowOpacity: 0.4,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 9,
  },
  goalCard: {
    marginTop: spacing.lg,
    borderRadius: 24,
    padding: spacing.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  goalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  goalLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: palette.textMuted,
  },
  goalValue: {
    marginTop: spacing.sm,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    letterSpacing: -1,
    color: palette.text,
  },
  goalTrack: {
    marginTop: spacing.md,
    height: 8,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: palette.ringTrack,
  },
  goalFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: palette.green,
  },
  editCard: {
    marginTop: spacing.md,
    borderRadius: 24,
    padding: spacing.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.stroke,
    shadowColor: palette.shadow,
    shadowOpacity: 0.15,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  editHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  editTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.text,
    letterSpacing: -0.2,
  },
  editMeta: {
    fontSize: 14,
    fontWeight: '500',
    color: palette.textMuted,
  },
  presetRow: {
    marginTop: spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  presetChip: {
    flex: 1,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  presetChipActive: {
    backgroundColor: palette.greenSoft,
    borderColor: palette.green,
  },
  presetChipText: {
    fontSize: 14,
    fontWeight: '600',
    color: palette.textMuted,
  },
  presetChipTextActive: {
    color: palette.greenDeep,
    fontWeight: '800',
  },
  editRow: {
    marginTop: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  editStepButton: {
    minWidth: 68,
    minHeight: 52,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceButton,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  editInputShell: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  editInput: {
    minWidth: 48,
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: -1,
    textAlign: 'center',
    color: palette.text,
  },
  editUnit: {
    marginLeft: spacing.xs,
    fontSize: 15,
    fontWeight: '600',
    color: palette.textMuted,
  },
  editActions: {
    marginTop: spacing.md,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  editGhostButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  editGhostText: {
    fontSize: 15,
    fontWeight: '700',
    color: palette.textMuted,
  },
  editApplyButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenDeep,
  },
  editApplyText: {
    fontSize: 15,
    fontWeight: '700',
    color: palette.white,
  },
  bottomActions: {
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  actionButton: {
    flex: 1,
    minHeight: 72,
    borderRadius: 22,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    backgroundColor: palette.surfaceButton,
    borderWidth: 1,
    borderColor: palette.stroke,
    shadowColor: palette.shadow,
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  actionCopy: {
    alignItems: 'flex-start',
  },
  actionLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.text,
  },
  actionHint: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: palette.textMuted,
  },
  });
}
