import { StyleSheet } from 'react-native';
import { spacing } from '../theme/tokens';
import { ScreenPalette } from '../theme/screenPalettes';

export function createInsightsStyles(palette: ScreenPalette, mode: 'dark' | 'light') {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: palette.backgroundTop,
    },
    content: {
      paddingHorizontal: spacing.md,
      paddingTop: spacing.md,
    },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: spacing.md,
    },
    topIconButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surfaceSoft,
      borderWidth: 1,
      borderColor: palette.stroke,
    },
    topTitle: {
      fontSize: 22,
      fontWeight: '900',
      color: palette.text,
      letterSpacing: -0.5,
    },
    tabRow: {
      flexDirection: 'row',
      backgroundColor: palette.surfaceSoft,
      padding: 6,
      borderRadius: 20,
      marginBottom: spacing.lg,
    },
    tabChip: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'transparent',
    },
    tabChipActive: {
      backgroundColor: palette.surface,
      borderColor: mode === 'dark' ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 0, 0, 0.06)',
      shadowColor: palette.shadow,
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 3,
    },
    tabChipText: {
      fontSize: 13,
      fontWeight: '900',
      color: palette.textSoft,
      textAlign: 'center',
    },
    tabChipTextActive: {
      color: palette.text,
      fontWeight: '900',
    },
    activeTabGlow: {
      position: 'absolute',
      bottom: -4,
      width: 20,
      height: 2,
      backgroundColor: palette.green,
      borderRadius: 1,
    },

    sectionCardGradient: {
      borderRadius: 28,
      padding: 1.5,
      shadowColor: palette.green,
      shadowOpacity: 0.25,
      shadowRadius: 20,
      elevation: 8,
    },
    sectionCardInner: {
      borderRadius: 26.5,
      padding: spacing.xl,
    },
    summaryCardGradient: {
      flex: 1,
      borderRadius: 24,
      padding: 1.5,
      shadowColor: palette.green,
      shadowOpacity: 0.2,
      shadowRadius: 15,
      elevation: 6,
    },
    summaryCardInner: {
      borderRadius: 22.5,
      padding: spacing.lg,
      flex: 1,
    },
    sectionCard: { 
      marginTop: spacing.lg, 
      borderRadius: 28, 
      padding: spacing.xl, 
      backgroundColor: palette.surface, 
      borderWidth: 1.5, 
      borderColor: palette.stroke,
      shadowColor: palette.green,
      shadowOpacity: 0.25,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: spacing.md },
    sectionTitle: { fontSize: 18, fontWeight: '800', color: palette.text },
    
    weekChip: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    navBtn: { padding: 4 },
    weekChipText: { fontSize: 13, fontWeight: '800', color: palette.text },

    periodToggle: { flexDirection: 'row', gap: 8, marginBottom: spacing.md },
    periodBtn: { 
      flex: 1, 
      paddingVertical: 10, 
      borderRadius: 12, 
      backgroundColor: mode === 'dark' ? 'rgba(255, 255, 255, 0.03)' : '#f8fafc', 
      alignItems: 'center',
      borderWidth: 1,
      borderColor: mode === 'dark' ? '#334155' : '#cbd5e1',
    },
    periodBtnActive: { 
      backgroundColor: mode === 'dark' ? 'rgba(16, 185, 129, 0.15)' : 'rgba(16, 185, 129, 0.06)', 
      borderWidth: 1.5, 
      borderColor: palette.green,
    },
    periodText: { 
      fontSize: 11, 
      fontWeight: '800', 
      color: mode === 'dark' ? '#cbd5e1' : '#475569',
    },
    periodTextActive: { color: palette.green, fontWeight: '900' },

    heroMinutes: { fontSize: 36, fontWeight: '900', color: palette.text, letterSpacing: -1 },
    heroMeta: { fontSize: 18, fontWeight: '700', color: palette.text, marginTop: -2 },
    heroDelta: { fontSize: 13, fontWeight: '700', color: palette.green, marginTop: 4 },

    chartContainer: { flexDirection: 'row', marginTop: 30, height: 140 },
    chartYAxis: { width: 35, justifyContent: 'space-between', paddingBottom: 22, height: 120 },
    chartYLabel: { fontSize: 11, fontWeight: '800', color: palette.textSoft, textAlign: 'right', paddingRight: 8 },
    chartArea: { flex: 1, height: 140, position: 'relative' },
    chartGrid: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 20, justifyContent: 'space-between' },
    chartGridLine: { height: 1, backgroundColor: palette.stroke, opacity: 0.5 },
    chartXLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8, paddingHorizontal: 4 },
    chartXLabel: { fontSize: 10, fontWeight: '900', color: palette.textSoft, textTransform: 'uppercase', letterSpacing: 0.5 },

    summaryGrid: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.md, width: '100%' },
    summaryCard: { 
      flex: 1, 
      padding: spacing.lg, 
      borderRadius: 24, 
      backgroundColor: palette.surface, 
      borderWidth: 1.5, 
      borderColor: palette.stroke,
      shadowColor: palette.green,
      shadowOpacity: 0.2,
      shadowRadius: 15,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
    summaryHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
    summaryIconWrap: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.greenSoft },
    summaryLabel: { fontSize: 11, fontWeight: '800', color: palette.textSoft, textTransform: 'uppercase', letterSpacing: 0.5 },
    summaryValue: { fontSize: 20, fontWeight: '800', color: palette.text },
    summarySub: { fontSize: 13, fontWeight: '600', color: palette.textSoft, marginTop: 2 },

    tripletGrid: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.lg },
    tripletCard: { 
      flex: 1, 
      paddingVertical: spacing.lg, 
      borderRadius: 20, 
      backgroundColor: palette.surfaceSoft, 
      borderWidth: 1.5, 
      borderColor: palette.stroke, 
      alignItems: 'center',
      shadowColor: palette.purple,
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
    tripletIcon: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
    tripletValue: { fontSize: 24, fontWeight: '900', color: palette.text },
    tripletLabel: { fontSize: 10, fontWeight: '800', color: palette.textSoft, textTransform: 'uppercase', marginTop: 2 },

    purifyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.lg },
    purifyBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10, backgroundColor: palette.greenSoft },
    purifyBadgeText: { fontSize: 11, fontWeight: '900', color: palette.green },
    
    timelineWrap: { marginTop: 30, paddingHorizontal: 4 },
    timelineRow: { height: 4, backgroundColor: palette.stroke, borderRadius: 2, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    timelineDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: palette.stroke },
    timelineDotActive: { backgroundColor: palette.purple, shadowColor: palette.purple, shadowOpacity: 0.5, shadowRadius: 8, elevation: 4 },
    timelineMeta: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
    timelineText: { fontSize: 11, fontWeight: '700', color: palette.textSoft },

    activityList: { marginTop: spacing.md },
    activityItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: palette.stroke },
    activityIconBox: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    activityInfo: { flex: 1, marginLeft: 12 },
    activityTitle: { fontSize: 15, fontWeight: '700', color: palette.text },
    activityMeta: { fontSize: 12, fontWeight: '600', color: palette.textSoft, marginTop: 2 },
    activityTime: { fontSize: 12, fontWeight: '700', color: palette.textSoft },

    metricSelector: { flexDirection: 'row', gap: 10, marginTop: spacing.md, marginBottom: spacing.xl },
    wellnessChartContainer: { marginTop: spacing.md },
    wellnessBars: { flexDirection: 'row', alignItems: 'flex-end', height: 180, gap: 12 },
    wellnessCol: { flex: 1, alignItems: 'center' },
    barTrack: { width: 14, height: 140, backgroundColor: palette.stroke + '30', borderRadius: 7, overflow: 'hidden', justifyContent: 'flex-end' },
    barFill: { width: '100%', borderRadius: 7 },
    barLabel: { fontSize: 10, fontWeight: '900', color: palette.textSoft, marginTop: 12, textTransform: 'uppercase' },
    wellnessBarValue: {
      fontSize: 9,
      fontWeight: '900',
      color: mode === 'dark' ? '#cbd5e1' : '#475569',
      marginBottom: 6,
      textAlign: 'center',
      height: 12,
    },

    metricBtn: { 
      flex: 1, 
      height: 44, 
      borderRadius: 14, 
      backgroundColor: mode === 'dark' ? 'rgba(255, 255, 255, 0.03)' : '#f8fafc', 
      flexDirection: 'row', 
      alignItems: 'center', 
      justifyContent: 'center', 
      gap: 6,
      borderWidth: 1.5,
      borderColor: mode === 'dark' ? '#334155' : '#cbd5e1',
    },
    metricBtnActive: { 
      backgroundColor: mode === 'dark' ? 'rgba(59, 130, 246, 0.15)' : 'rgba(59, 130, 246, 0.06)', 
      borderWidth: 1.5, 
      borderColor: palette.blue, 
    },
    metricText: { 
      fontSize: 12, 
      fontWeight: '800', 
      color: mode === 'dark' ? '#cbd5e1' : '#475569',
    },
    metricTextActive: { color: palette.blue, fontWeight: '900' },

    seeAllBtn: { 
      marginTop: 16, 
      paddingVertical: 12, 
      alignItems: 'center', 
      borderTopWidth: 1, 
      borderColor: palette.stroke,
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 4
    },
    seeAllText: { fontSize: 13, fontWeight: '800', color: palette.blue },
  });
}
