import { StyleSheet } from 'react-native';
import { spacing } from '../theme/tokens';

export const darkPalette = {
  backgroundTop: '#0f111a',
  backgroundBottom: '#181124',
  screenGlow: 'rgba(0, 255, 170, 0.25)',
  screenGlowSoft: 'rgba(255, 51, 153, 0.2)',
  screenGlowAccent: 'rgba(51, 153, 255, 0.25)',
  surface: 'rgba(255, 255, 255, 0.12)',
  surfaceSoft: 'rgba(255, 255, 255, 0.08)',
  stroke: 'rgba(255, 255, 255, 0.2)',
  text: '#ffffff',
  textMuted: '#e2e8f0',
  textSoft: '#94a3b8',
  purpleTrack: 'rgba(255, 255, 255, 0.15)',
  purple: '#d946ef',
  purpleGlow: 'rgba(217, 70, 239, 0.25)',
  green: '#00ff9d',
  iconAccent: '#ff4b4b',
  yellow: '#fbbf24',
  shadow: 'rgba(0, 0, 0, 0.5)',
  activeToggleBg: '#56cce9ff',
  flashAccent: '#00ff9d',
  powerAccent: '#d500f9',
  iconColor:'#07ea4fff',
  powerBackground:'#f9f2f2ff'
};

export const lightPalette = {
  backgroundTop: '#e8f5e9',
  backgroundBottom: '#f3e5f5',
  screenGlow: 'rgba(0, 200, 83, 0.15)',
  screenGlowSoft: 'rgba(170, 0, 255, 0.12)',
  screenGlowAccent: 'rgba(41, 98, 255, 0.15)',
  surface: 'rgba(255, 255, 255, 0.8)',
  surfaceSoft: 'rgba(255, 255, 255, 0.6)',
  stroke: 'rgba(255, 255, 255, 0.9)',
  text: '#0f172a',
  textMuted: '#475569',
  textSoft: '#94a3b8',
  purpleTrack: 'rgba(0, 0, 0, 0.04)',
  purple: '#8b5cf6',
  purpleGlow: 'rgba(139, 92, 246, 0.2)',
  green: '#10b981',
  iconAccent: '#dc2626',
  yellow: '#d97706',
  shadow: 'rgba(0, 0, 0, 0.06)',
  activeToggleBg: '#56cce9ff',
  flashAccent: '#0d9488',
  powerAccent: '#121213ff',
  powerBackground:'#d442abff',
  iconColor:'#05f128ff',
};

export type ScreenPalette = typeof darkPalette & {
  screenGlow: string;
  screenGlowSoft: string;
  screenGlowAccent: string;
};

export function createPurifyStyles(palette: ScreenPalette) {
  return StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.backgroundTop,
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  topTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.text,
  },
  toggleShell: {
    flexDirection: 'row',
    borderRadius: 18,
    padding: 4,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  toggleOption: {
    minWidth: 40,
    minHeight: 30,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  toggleOptionActive: {
    backgroundColor: palette.activeToggleBg,
  },
  toggleText: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.text,
  },
  headerBlock: {
    marginTop: spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
  },
  screenTitle: {
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '800',
    color: palette.text,
    textAlign: 'left',
    letterSpacing: -0.5,
  },
  screenSubtitle: {
    marginTop: spacing.xs,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '500',
    textAlign: 'left',
    color: palette.textMuted,
  },
  ringSection: {
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringAtmosphere: {
    position: 'absolute',
  },
  ringOverlay: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topRightPowerBtn: {
    position: 'absolute',
    right: 16,
    bottom: 26,
    width:48,
    height:48,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: palette.stroke,
    shadowColor: palette.powerAccent,
    color: palette.iconColor,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    backgroundColor: palette.powerBackground,
  },
  iconColor:{
    color: palette.iconColor,
   
  },
  
  iconSquircle: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  dayLabel: {
    fontSize: 22,
    fontWeight: '700',
    color: palette.textMuted,
    textAlign: 'center',
  },
  timerLabel: {
    marginTop: 8,
    fontSize: 48,
    lineHeight: 52,
    fontWeight: '800',
    color: palette.text,
    textAlign: 'center',
    letterSpacing: -1,
  },
  rainbowSvg: {
    alignSelf: 'center',
  },
  walkIconCircle: {
    marginTop: 16,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextMilestoneCard: {
    marginTop: spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
    backgroundColor: palette.surfaceSoft,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  milestoneIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: palette.purpleGlow,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  milestoneCopy: {
    flex: 1,
  },
  milestoneLabelSmall: {
    fontSize: 14,
    color: palette.textSoft,
    fontWeight: '600',
  },
  milestoneValueLarge: {
    marginTop: 4,
    fontSize: 18,
    color: palette.purple,
    fontWeight: '800',
  },
  quoteGlassCard: {
    marginTop: spacing.md,
    flexDirection: 'row',
    backgroundColor: palette.surfaceSoft,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.stroke,
    overflow: 'hidden',
  },
  quoteLeftBar: {
    width: 4,
    backgroundColor: palette.green,
  },
  quoteContent: {
    flex: 1,
    padding: spacing.md,
  },
  quoteTextMain: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: palette.text,
  },
  quoteSourceText: {
    marginTop: spacing.sm,
    fontSize: 13,
    color: palette.textMuted,
    fontWeight: '500',
  },
  openFocusButton: {
    marginTop: spacing.md,
    marginBottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    height: 60,
    backgroundColor: palette.surfaceSoft,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  openFocusText: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.yellow,
  },
  });
}
