import { StyleSheet } from 'react-native';
import { spacing } from '../theme/tokens';
import { ScreenPalette } from '../theme/screenPalettes';

export function createPurifyStyles(palette: ScreenPalette) {
  return StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.backgroundTop,
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  topTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.text,
  },
  toggleShell: {
    flexDirection: 'row',
    borderRadius: 18,
    padding: 4,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  toggleOption: {
    minWidth: 40,
    minHeight: 30,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  toggleOptionActive: {
    backgroundColor: palette.activeToggleBg,
  },
  toggleText: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.text,
  },
  headerBlock: {
    marginTop: spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
  },
  screenTitle: {
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '800',
    color: palette.text,
    textAlign: 'left',
    letterSpacing: -0.5,
  },
  screenSubtitle: {
    marginTop: spacing.xs,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '500',
    textAlign: 'left',
    color: palette.textMuted,
  },
  ringSection: {
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringAtmosphere: {
    position: 'absolute',
  },
  ringOverlay: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topRightPowerBtn: {
    position: 'absolute',
    right: 16,
    bottom: 26,
    width:48,
    height:48,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: palette.stroke,
    shadowColor: palette.powerAccent,
    color: palette.iconColor,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    backgroundColor: palette.powerBackground,
  },
  iconColor:{
    color: palette.iconColor,
   
  },
  
  iconSquircle: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  dayLabel: {
    fontSize: 22,
    fontWeight: '700',
    color: palette.textMuted,
    textAlign: 'center',
  },
  timerLabel: {
    marginTop: 8,
    fontSize: 48,
    lineHeight: 52,
    fontWeight: '800',
    color: palette.text,
    textAlign: 'center',
    letterSpacing: -1,
  },
  rainbowSvg: {
    alignSelf: 'center',
  },
  walkIconCircle: {
    marginTop: 16,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextMilestoneCard: {
    marginTop: spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
    backgroundColor: palette.surfaceSoft,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  milestoneIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: palette.purpleGlow,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  milestoneCopy: {
    flex: 1,
  },
  milestoneLabelSmall: {
    fontSize: 14,
    color: palette.textSoft,
    fontWeight: '600',
  },
  milestoneValueLarge: {
    marginTop: 4,
    fontSize: 18,
    color: palette.purple,
    fontWeight: '800',
  },
  quoteGlassCard: {
    marginTop: spacing.md,
    flexDirection: 'row',
    backgroundColor: palette.surfaceSoft,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.stroke,
    overflow: 'hidden',
  },
  quoteLeftBar: {
    width: 4,
    backgroundColor: palette.green,
  },
  quoteContent: {
    flex: 1,
    padding: spacing.md,
  },
  quoteTextMain: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: palette.text,
  },
  quoteSourceText: {
    marginTop: spacing.sm,
    fontSize: 13,
    color: palette.textMuted,
    fontWeight: '500',
  },
  openFocusButton: {
    marginTop: spacing.md,
    marginBottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    height: 60,
    backgroundColor: palette.surfaceSoft,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  openFocusText: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.yellow,
  },
  });
}
