import { StyleSheet, StatusBar as RNStatusBar } from 'react-native';
import { spacing, typography } from '../theme/tokens';

export const darkPalette = {
  backgroundTop: '#121c29',
  backgroundBottom: '#172334',
  screenGlow: 'rgba(120, 220, 140, 0.1)',
  screenGlowSoft: 'rgba(136, 168, 255, 0.08)',
  surface: 'rgba(255, 255, 255, 0.12)',
  surfaceSoft: 'rgba(255, 255, 255, 0.08)',
  surfaceMuted: 'rgba(255, 255, 255, 0.04)',
  stroke: 'rgba(255, 255, 255, 0.2)',
  text: '#ffffff',
  textMuted: '#e2e8f0',
  textSoft: '#94a3b8',
  white: '#ffffff',
  green: '#78dc8c',
  greenDeep: '#355f3f',
  greenSoft: 'rgba(120, 220, 140, 0.16)',
  blue: '#8db0ff',
  blueSoft: 'rgba(141, 176, 255, 0.16)',
  red: '#ff8e88',
  redSoft: 'rgba(255, 142, 136, 0.14)',
  shadow: 'rgba(3, 9, 18, 0.34)',
};

export const lightPalette = {
  backgroundTop: '#eef5f0',
  backgroundBottom: '#f8fbf8',
  screenGlow: 'rgba(31, 165, 91, 0.05)',
  screenGlowSoft: 'rgba(46, 111, 242, 0.04)',
  surface: 'rgba(255, 255, 255, 0.98)',
  surfaceSoft: 'rgba(250, 252, 250, 0.98)',
  surfaceMuted: 'rgba(241, 246, 242, 0.98)',
  stroke: 'rgba(19, 32, 24, 0.08)',
  text: '#132018',
  textMuted: '#425149',
  textSoft: '#64736c',
  white: '#ffffff',
  green: '#1fa55b',
  greenDeep: '#1f7a46',
  greenSoft: 'rgba(31, 165, 91, 0.1)',
  blue: '#2e6ff2',
  blueSoft: 'rgba(46, 111, 242, 0.08)',
  red: '#d9534f',
  redSoft: 'rgba(217, 83, 79, 0.08)',
  shadow: 'rgba(19, 32, 24, 0.14)',
};

export type ScreenPalette = typeof darkPalette;

export function createQuickStartStyles(palette: ScreenPalette) {
  return StyleSheet.create({
  safeArea: {
    flex: 1,
    marginTop: RNStatusBar.currentHeight,
    backgroundColor: palette.backgroundTop,
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.xl,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  topTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: palette.text,
  },
  badge: {
    minHeight: 42,
    borderRadius: 21,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
    borderWidth: 1,
    borderColor: 'rgba(120, 220, 140, 0.1)',
  },
  badgeText: {
    fontSize: typography.caption,
    fontWeight: '800',
    color: palette.green,
  },
  helperText: {
    marginTop: spacing.lg,
    maxWidth: 240,
    fontSize: 16,
    lineHeight: 24,
    color: palette.textMuted,
  },
  metricsRow: {
    marginTop: spacing.lg,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  metricCard: {
    flex: 1,
    minHeight: 86,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  metricCardGreen: {
    backgroundColor: palette.greenSoft,
  },
  metricCardBlue: {
    backgroundColor: palette.blueSoft,
  },
  metricCardRed: {
    backgroundColor: palette.redSoft,
  },
  metricValue: {
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '900',
    color: palette.text,
  },
  metricLabel: {
    marginTop: 4,
    fontSize: typography.caption,
    fontWeight: '700',
    color: palette.textMuted,
  },
  card: {
    marginTop: spacing.lg,
    borderRadius: 24,
    padding: spacing.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.stroke,
    shadowColor: palette.shadow,
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  cardEyebrow: {
    fontSize: typography.caption,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: palette.textSoft,
  },
  cardTitle: {
    marginTop: spacing.xs,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '800',
    color: palette.text,
  },
  cardIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surfaceMuted,
  },
  cardSubtitle: {
    marginTop: spacing.sm,
    fontSize: 16,
    lineHeight: 24,
    color: palette.textMuted,
  },
  actionsList: {
    marginTop: spacing.md,
    gap: spacing.sm,
  },
  actionButton: {
    minHeight: 74,
    borderRadius: 22,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.stroke,
  },
  actionButtonPrimary: {
    backgroundColor: palette.greenDeep,
    borderColor: 'rgba(120, 220, 140, 0.24)',
    shadowColor: palette.green,
    shadowOpacity: 0.26,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  actionButtonDanger: {
    backgroundColor: 'rgba(88, 41, 45, 0.6)',
    borderColor: 'rgba(255, 142, 136, 0.22)',
  },
  actionIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  actionIconWrapPrimary: {
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  actionIconWrapDanger: {
    backgroundColor: 'rgba(255, 142, 136, 0.14)',
  },
  actionCopy: {
    flex: 1,
  },
  actionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: palette.text,
  },
  actionTitlePrimary: {
    color: palette.white,
  },
  actionTitleDanger: {
    color: palette.red,
  },
  actionSubtitle: {
    marginTop: 2,
    fontSize: 14,
    lineHeight: 19,
    color: palette.textMuted,
  },
  });
}
